# This is a basic workflow to help you get started with Actions

name: weekly update

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name : git commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b weekly-update
          git commit --allow-empty -m "weekly update"
          git push origin weekly-update
